# Generated by Django 3.0.8 on 2020-08-03 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('nutri_score', models.CharField(max_length=1, null=True)),
                ('link', models.TextField()),
                ('details', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.Categories', verbose_name="product's category")),
                ('purchase_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitute.PurchaseStores', verbose_name='purchase store')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's favorites substitutes")),
                ('product_replaced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced', to='substitute.Products', verbose_name='replaced product')),
                ('product_replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_substitute', to='substitute.Products', verbose_name='substitute')),
            ],
        ),
    ]
