# Generated by Django 3.0.8 on 2020-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0003_auto_20200805_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='nutriscore',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
