# Generated by Django 3.0.8 on 2020-08-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_auto_20200805_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='link',
            new_name='barcode',
        ),
    ]
