# Generated by Django 3.0.8 on 2020-08-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20200816_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='substitute.Categories', verbose_name="product's categories"),
        ),
    ]
