# Generated by Django 3.0.8 on 2020-08-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0006_auto_20200816_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='purchasestores',
            old_name='store_name',
            new_name='name',
        ),
    ]
