# Generated by Django 3.0.8 on 2020-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0007_auto_20200825_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='en_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
