# Generated by Django 3.0.8 on 2020-10-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0009_products_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='product_replaced',
        ),
    ]
